{{- if or (and (not .Values.secrets.existingSecret) (not .Values.env.LLDAP_JWT_SECRET) (not .Values.env.LLDAP_KEY_SEED) (not .Values.env.LLDAP_LDAP_USER_PASS) (not .Values.env.LLDAP_LDAP_USER_DN )) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lldap.secretsname" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  jwt-secret: {{ (tpl .Values.secrets.lldapJwtSecret .) | default ( randAlphaNum 32 ) | b64enc | quote }}
  key-seed: {{ (tpl .Values.secrets.lldapKeySeed  .) | default ( randAlphaNum 12 ) | b64enc | quote }}
  ldap-user-dn:  {{ .Values.secrets.lldapUser | b64enc | quote }}
  ldap-user-pass: {{ (tpl .Values.secrets.lldapUserPass  .) | default ( randAlphaNum 12 ) | b64enc | quote }}
  {{- if and (not .Values.env.LLDAP_DATABASE_URL) }}
  database-url: {{ include "lldap.postgres_url" . | quote }}
  {{- end }}
{{- end }}