
{{- if .Values.persistence.config.enabled -}}
{{- if not .Values.persistence.config.existingClaim -}}
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ template "homarr.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.persistence.config.annotations }}
  {{ toYaml .Values.persistence.config.annotations | indent 2 }}  
  {{ end }}
  labels:
    {{- include "homarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
  {{ end }}
  {{- if .Values.persistence.config.selector }}
  selector:
{{ toYaml .Values.persistence.config.selector | indent 4 }}
  {{ end }}
{{- end }}
{{- end }}