
{{- if .Values.persistence.data.enabled -}}
{{- if not .Values.persistence.data.existingClaim -}}
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ template "homarr.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.persistence.data.annotations }}
  {{ toYaml .Values.persistence.data.annotations | indent 2 }}  
  {{ end }}
  labels:
    {{- include "homarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{ end }}
  {{- if .Values.persistence.data.selector }}
  selector:
{{ toYaml .Values.persistence.data.selector | indent 4 }}
  {{ end }}
{{- end }}
{{- end }}